### ISSUE TITLE
More auto-generated pages, lists and links

### ISSUE THREAD

**Issue by bittlingmayer** [machinetranslate/machinetranslate.org#303]
We currently only have an [auto-gen layout for language pages](https://github.com/machinetranslate/machinetranslate.org/blob/master/_layouts/language.html) and [the auto-gen script](https://github.com/machinetranslate/machinetranslate.org/blob/master/generate.py) only generates pages for languages.

Add auto-gen **layouts** for:
- [x] TMSes
- [x] engines
- [x] Make auto-gen layout for language families
- [x] Make auto-gen layout for scripts

Update the auto-gen **script** to include:
- [ ] TMS pages
- [ ] engine pages
- [ ] language family pages
- [ ] script pages

Auto-gen lists
- [ ] All events
- [ ] All engines
- [ ] All TMSes
- [ ] All scripts
- [ ] All language *pairs*
- [ ] All language families
Only engines and TMSes need to be in the sidebar.

Linking
- [ ] In language page card, link: language family, scripts, typology
- [ ] In engine page card, link: languages, TMSes

Integrity checking 
- [ ] Script to make sure that every engine language is in the languages data file
- [ ] Script to make sure that every language’s script is in the scripts data file
- [ ] Script to make sure that every language’s family is in the language families file

Other integrity checking
- [ ] Check for missing links

**Comment by cefoo** [comment]
> Only engines and TMSes need to be in the sidebar.

No TMSes in the sidebar 😊
